spring.application.name=EmployeeManagement

server.port = 1234
#database connection properties
spring.datasource.url=jdbc:mysql://localhost:3306/cts
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
 
 
 #hibernate properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#line 13 use for to tell jap use hibernate and generate quries
management.endpoints.web.exposure.include=*
